<a href="https://colab.research.google.com/github/kimlind/ztm-pytorch-for-deeplearning/blob/main/00_pytorch_fundametals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)


2.1.0+cu118


## Introduction to tensors

### Creating tensors

PyTorch tensors are created using `torc.tensor()`

In [2]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
scalar.item()

7

In [5]:
#Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim


1

In [7]:
vector.shape

torch.Size([2])

In [8]:
#Matrix
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX.shape

torch.Size([2, 2])

In [11]:
# Tensor
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]],[[2,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]],

        [[2, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [12]:
TENSOR.ndim

3

In [13]:
TENSOR.shape

torch.Size([2, 3, 3])

In [14]:
TENSOR[1]

tensor([[2, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random tensors

Why random tensors?

random tensors are important because the way neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [15]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(2, 3, 4)
random_tensor

tensor([[[0.3218, 0.7319, 0.4540, 0.4463],
         [0.8497, 0.2765, 0.3697, 0.2847],
         [0.1829, 0.3730, 0.9929, 0.1439]],

        [[0.3774, 0.3350, 0.4316, 0.7634],
         [0.8783, 0.8631, 0.2556, 0.6883],
         [0.2733, 0.9861, 0.3443, 0.4616]]])

In [16]:
# Create a random tensor with similar shape to in image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) #Height, width, Color channel

In [17]:
random_image_size_tensor.ndim

3

### Zeros and ones



In [18]:
#Create a tensor of all zeros

zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [19]:
# Create a tensor of all ones
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### Create a range of tensors tensors-like

In [20]:
# use torch.range
torch.range(0,10)

<ipython-input-20-255291c05083>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [21]:
# Use torcharange
one_to_ten = torch.arange(1,11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
# Create tensors like
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big error youll run into with PyTorch & deep learning

1. Tensor not right datatype
2. Tensor not right shape
3. Tensor Not on the right device

In [24]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0], dtype=torch.float16) # What data type is tensor
float_32_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [26]:
float_32_tensor = torch.tensor([3.0,6.0,9.0], device=None) # What device is your tensor on
float_32_tensor

tensor([3., 6., 9.])

In [27]:
float_32_tensor = torch.tensor([3.0,6.0,9.0], requires_grad=False) # Whether or not track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [29]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

### Getting information from tensors

1. Tensor not right datatype -> tensor.dtype
2. Tensor not right shape -> tensor.shape
3. Tensor Not on the right device -> tensor.device



In [32]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.3538, 0.6606, 0.7984, 0.9783],
        [0.9542, 0.9631, 0.3767, 0.1666],
        [0.6430, 0.2781, 0.0268, 0.4269]])

In [33]:
# Find some details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"device of tensor: {some_tensor.device}")

tensor([[0.3538, 0.6606, 0.7984, 0.9783],
        [0.9542, 0.9631, 0.3767, 0.1666],
        [0.6430, 0.2781, 0.0268, 0.4269]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
device of tensor: cpu


### Manipulating tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Divisiom
* Matrix multiplication

In [34]:
# Create tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [35]:
# Multiply by ten
tensor * 10

tensor([10, 20, 30])

In [36]:
# Subtract ten
tensor - 10

tensor([-9, -8, -7])

In [37]:
# Try out PyTorch inbuild functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [38]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix multiplication

Two main ways of performing multiplication in neural network and deep learning:

1. Element wise multiplication
2. Matrix Multiplication (dot product)

https://www.mathsisfun.com/algebra/matrix-multiplying.html


In [39]:
# Element wise multiplication
print(tensor * tensor)

tensor([1, 4, 9])


In [40]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [41]:
# Matrix multiplication
print(sum(tensor * tensor))

tensor(14)


In [47]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i]*tensor[i]
print(value)

tensor(14)
CPU times: user 2.33 ms, sys: 0 ns, total: 2.33 ms
Wall time: 2.34 ms


In [45]:
%%time
print(torch.matmul(tensor, tensor))

tensor(14)
CPU times: user 2.3 ms, sys: 0 ns, total: 2.3 ms
Wall time: 2.32 ms


In [46]:
%%time
print(sum(tensor * tensor))

tensor(14)
CPU times: user 1.7 ms, sys: 991 µs, total: 2.69 ms
Wall time: 2.65 ms
