<a href="https://colab.research.google.com/github/kimlind/ztm-pytorch-for-deeplearning/blob/first-lesson/00_pytorch_fundametals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)


2.1.0+cu118


## Introduction to tensors

### Creating tensors

PyTorch tensors are created using `torc.tensor()`

In [ ]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

7

In [ ]:
#Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim


1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
#Matrix
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# Tensor
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]],[[2,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]],

        [[2, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([2, 3, 3])

In [ ]:
TENSOR[1]

tensor([[2, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random tensors

Why random tensors?

random tensors are important because the way neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [ ]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(2, 3, 4)
random_tensor

tensor([[[0.3173, 0.1938, 0.5454, 0.2315],
         [0.2580, 0.3931, 0.6249, 0.3774],
         [0.4765, 0.4308, 0.0083, 0.1978]],

        [[0.1282, 0.3776, 0.3147, 0.7124],
         [0.2280, 0.6981, 0.7442, 0.8832],
         [0.9568, 0.2282, 0.3588, 0.8131]]])

In [ ]:
# Create a random tensor with similar shape to in image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) #Height, width, Color channel

In [ ]:
random_image_size_tensor.ndim

3

### Zeros and ones



In [ ]:
#Create a tensor of all zeros

zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# Create a tensor of all ones
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### Create a range of tensors tensors-like

In [ ]:
# use torch.range
torch.range(0,10)

<ipython-input-20-255291c05083>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
# Use torcharange
one_to_ten = torch.arange(1,11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# Create tensors like
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big error youll run into with PyTorch & deep learning

1. Tensor not right datatype
2. Tensor not right shape
3. Tensor Not on the right device

In [ ]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0], dtype=torch.float16) # What data type is tensor
float_32_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_32_tensor = torch.tensor([3.0,6.0,9.0], device=None) # What device is your tensor on
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor = torch.tensor([3.0,6.0,9.0], requires_grad=False) # Whether or not track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

### Getting information from tensors

1. Tensor not right datatype -> tensor.dtype
2. Tensor not right shape -> tensor.shape
3. Tensor Not on the right device -> tensor.device



In [ ]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.3810, 0.7237, 0.8526, 0.5446],
        [0.7421, 0.2012, 0.7218, 0.8491],
        [0.6347, 0.1491, 0.1473, 0.4759]])

In [ ]:
# Find some details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"device of tensor: {some_tensor.device}")

tensor([[0.3810, 0.7237, 0.8526, 0.5446],
        [0.7421, 0.2012, 0.7218, 0.8491],
        [0.6347, 0.1491, 0.1473, 0.4759]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
device of tensor: cpu


### Manipulating tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Divisiom
* Matrix multiplication

In [ ]:
# Create tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
# Multiply by ten
tensor * 10

tensor([10, 20, 30])

In [ ]:
# Subtract ten
tensor - 10

tensor([-9, -8, -7])

In [ ]:
# Try out PyTorch inbuild functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [ ]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix multiplication

Two main ways of performing multiplication in neural network and deep learning:

1. Element wise multiplication
2. Matrix Multiplication (dot product)

https://www.mathsisfun.com/algebra/matrix-multiplying.html

There are two main rules in matrix multiplicaiton
1. The **inner dimensions** must match:
* `(3,2) @ (3,2)` wont work
* `(2,3) @ (3,2)` will work
* `(3,2) @ (2,3)` will work

2. The resulting matrix has the shape of the **outer dimensions**:
* `(2,3) @ (3,2)` -> `(2,2)`
* `(3,2) @ (2,3)` -> `(3,3)`


In [ ]:
# Element wise multiplication
print(tensor * tensor)

tensor([1, 4, 9])


In [ ]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
# Matrix multiplication
print(sum(tensor * tensor))

tensor(14)


In [ ]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i]*tensor[i]
value

CPU times: user 221 µs, sys: 1.05 ms, total: 1.27 ms
Wall time: 1.22 ms


tensor(14)

In [ ]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 86 µs, sys: 0 ns, total: 86 µs
Wall time: 91.1 µs


tensor(14)

In [ ]:
%%time
sum(tensor * tensor)

CPU times: user 224 µs, sys: 0 ns, total: 224 µs
Wall time: 234 µs


tensor(14)

### One of the most common errors in deep learning is shape error



In [ ]:
# Shapes for matrix multiplications

tensor_a = torch.rand(3,2)
tensor_b = torch.rand(3,2)
#torch.mm(tensor_a, tensor_b) # mm is alias to matmul

RuntimeError: ignored

To fix our tensor shape issues, we can manipulate the shape of one our tensors using torch.transpose

A ***transpose*** switches the axes or dimension of a given tensor

In [ ]:
tensor_b.T, tensor_b.T.shape

(tensor([[0.1994, 0.6505, 0.6318],
         [0.5742, 0.2746, 0.8162]]),
 torch.Size([2, 3]))

In [ ]:
# The matrix multiplication works when tensor b is transposed

torch.matmul(tensor_a, tensor_b.T)

tensor([[0.4491, 0.5919, 0.8750],
        [0.3790, 0.7278, 0.8817],
        [0.5581, 0.3766, 0.8621]])

## Finding min, max, sum etc tensor aggregation

In [ ]:
# create tensor
x = torch.arange(0, 100, 10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [ ]:
#Find min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [ ]:
# Find max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
# find mean. Mean function requires float or complex data type
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [ ]:
# Find sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

## Finding the positional min and max

In [ ]:
torch.argmin(x), x.argmin()

(tensor(0), tensor(0))

In [ ]:
torch.argmax(x), x.argmax()

(tensor(9), tensor(9))

## Reshaping, stacking, squeezing, unsqueezing tensors

* Reshaping - Reshapes an input to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - remove all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to target tensor
* permute - return a view of the input with dimension permuted (swapped) in a certain way

In [ ]:
# Create tensor
x = torch.arange(1., 10.)

In [ ]:
# Add an extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Changing z changes x as they share the same memory
z[:,0] = 5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked, x_stacked.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 torch.Size([4, 9]))

In [ ]:
# Squeeze removes all single dimensions from target tensor
x_squeezed = x_reshaped.squeeze()
x_reshaped, x_reshaped.squeeze()

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# Unsqueeze - adds a single dimension to target tensor at specific dim (dimension)
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add extra dimension
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew shape: {x_unsqueezed.shape}")
x_unsqueezed

Previous target: tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New shape: torch.Size([1, 9])


tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
# Permute - rearranges the dimensrions of a target in specific order
x_original = torch.rand(224, 448,3) # Height, width, colour channel

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1)
x_permuted.shape

torch.Size([3, 224, 448])

In [ ]:
# permuted matrix share the memory of the original
x_original[0,0,0] = 666
x_permuted[0,0,0]

tensor(666.)

## Indexing (Selecting data from tensors)
Indexing with PyTorch is similar indexing with numpy

In [ ]:
# Create a tensor
x = torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
# Index
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
x[0,0]

tensor([1, 2, 3])

In [ ]:
x[0,0,0]

tensor(1)

In [ ]:
# You can also use semicolon ":" to select all of the target dimension
x[:,0]

tensor([[1, 2, 3]])

In [ ]:
x[:,:,0]

tensor([[1, 4, 7]])

In [ ]:
x[:,1,:]

tensor([[4, 5, 6]])

In [ ]:
x[0,0,:]

tensor([1, 2, 3])

## Pytorch tensors & Numpy
Numpy is a popular scientific python computing library and because of this, PyTorch has functionality to interact with it

* Data in numpy, want in pytorch tensor -> torch.from_numpy(ndarray)
* PyTorch tensor -> numpy -> torch.Tensor.numpy()


In [ ]:
# numpy array to tensor
array = np.arange(1.,8.)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Tensor to Numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (Trying to take random out of random

in short how neural network learns:
* start with random numbers
* tensor operations
* update random numbers to try and make them better representations of the data
* repeat

To reduce randomness in neural networks and pytorch comes the concept of a **random seed**

Essentially what random seed does "flavour" the randomness



In [ ]:
#Create two random tensors
random_tensor_a = torch.rand(3,4)
random_tensor_b = torch.rand(3,4)

print(random_tensor_a)
print(random_tensor_b)
print(random_tensor_a==random_tensor_b)

tensor([[0.5222, 0.9820, 0.9735, 0.3678],
        [0.0416, 0.8857, 0.4762, 0.6881],
        [0.1255, 0.9288, 0.3466, 0.4986]])
tensor([[0.8089, 0.4038, 0.7984, 0.9295],
        [0.2762, 0.0503, 0.8120, 0.0271],
        [0.1781, 0.2790, 0.5690, 0.9942]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# random but reprodcible tensors
RANDOM_SEED = 1308
torch.manual_seed(RANDOM_SEED)
random_tensor_c = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
random_tensor_d = torch.rand(3,4)

print(random_tensor_c)
print(random_tensor_d)
print(random_tensor_c==random_tensor_d)

tensor([[0.4482, 0.7059, 0.8577, 0.5445],
        [0.2432, 0.3827, 0.8384, 0.3263],
        [0.9527, 0.8818, 0.4119, 0.7190]])
tensor([[0.4482, 0.7059, 0.8577, 0.5445],
        [0.2432, 0.3827, 0.8384, 0.3263],
        [0.9527, 0.8818, 0.4119, 0.7190]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and pytoirch objects on GPU(faster computing)

GPU = faster computation on numbers

### 1. Getting GPU

1. Easiest - Google Colab free
2. Use your own - Takes little bit of setup
3. Use cloud computing - GCP, AWS, Azure...


In [1]:
!nvidia-smi

Mon Dec  4 15:35:27 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   42C    P8     9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

### 2. Check for GPU Access with Pytorch

In [3]:
# Check for GPU access with pytorch
import torch
torch.cuda.is_available()

True

In [5]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

For pytorch since its capable of running compute on gpu or CPU, its best practise to setup device agnostic code. E.g run on GPU if available else default to CPU

In [6]:
# Count number of devices
torch.cuda.device_count()

1

### 3. Putting tensors  (and models) on the GPU

The reason we want our models on the GPU is beacause GPU results in faster computation

In [7]:
# Create tensor (default to cpu)
tensor = torch.tensor([1,2,3], device="cpu")

print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [9]:
# move tensor to gpu if available
tensor_on_gpu= tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [12]:
### 4. Moving tensors back to cpu for numpy
tensor_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_on_cpu

array([1, 2, 3])

##  Exercises & Extra curriculum